name: My First Workflow
on:
  push:
    branches: 
      -main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: color generator
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: color receiver
        run: echo "${{steps.color-generator.outputs.SELECTED_COLOR }}"
